export const SET_DESCRIPTORS = "SET_DESCRIPTORS";
export const SET_DESCRIPTORS_REFERENCES = "SET_DESCRIPTORS_REFERENCES";
export const SET_LOADING_DESCRIPTORS = "SET_LOADING_DESCRIPTORS";
export const UPDATE_REFERENCE_ID = "UPDATE_REFERENCE_ID";
export const CLEAR_DESCRIPTORS = "CLEAR_DESCRIPTORS";
export const SET_MODULE_ID = "SET_MODULE_ID";
